title: Sen Li's Homepage
page-top-title: Gao Jiaze
top-section-bg-text: Cross-disciplinary Technologies +
home-subtitle: Gao Jiaze&ensp;|&ensp;高嘉泽
copyright-text: '&copy; Gao Jiaze 2023-2024. All Rights Reserved.'
